// capital: the answer. cities: other well-known cities in the same state,
// used as distractors in Cities mode. None of them is the capital.
window.STATES = [
  { name: "Alabama",        abbr: "AL", capital: "Montgomery",     cities: ["Birmingham", "Huntsville", "Mobile", "Tuscaloosa"] },
  { name: "Alaska",         abbr: "AK", capital: "Juneau",         cities: ["Anchorage", "Fairbanks", "Sitka", "Wasilla"] },
  { name: "Arizona",        abbr: "AZ", capital: "Phoenix",        cities: ["Tucson", "Mesa", "Scottsdale", "Flagstaff"] },
  { name: "Arkansas",       abbr: "AR", capital: "Little Rock",    cities: ["Fayetteville", "Fort Smith", "Springdale", "Jonesboro"] },
  { name: "California",     abbr: "CA", capital: "Sacramento",     cities: ["Los Angeles", "San Diego", "San Jose", "San Francisco"] },
  { name: "Colorado",       abbr: "CO", capital: "Denver",         cities: ["Colorado Springs", "Aurora", "Fort Collins", "Boulder"] },
  { name: "Connecticut",    abbr: "CT", capital: "Hartford",       cities: ["Bridgeport", "New Haven", "Stamford", "Waterbury"] },
  { name: "Delaware",       abbr: "DE", capital: "Dover",          cities: ["Wilmington", "Newark", "Middletown", "Smyrna"] },
  { name: "Florida",        abbr: "FL", capital: "Tallahassee",    cities: ["Jacksonville", "Miami", "Tampa", "Orlando"] },
  { name: "Georgia",        abbr: "GA", capital: "Atlanta",        cities: ["Savannah", "Augusta", "Columbus", "Macon"] },
  { name: "Hawaii",         abbr: "HI", capital: "Honolulu",       cities: ["Hilo", "Kailua", "Kaneohe", "Pearl City"] },
  { name: "Idaho",          abbr: "ID", capital: "Boise",          cities: ["Meridian", "Nampa", "Idaho Falls", "Coeur d'Alene"] },
  { name: "Illinois",       abbr: "IL", capital: "Springfield",    cities: ["Chicago", "Naperville", "Rockford", "Peoria"] },
  { name: "Indiana",        abbr: "IN", capital: "Indianapolis",   cities: ["Fort Wayne", "Evansville", "South Bend", "Bloomington"] },
  { name: "Iowa",           abbr: "IA", capital: "Des Moines",     cities: ["Cedar Rapids", "Davenport", "Sioux City", "Iowa City"] },
  { name: "Kansas",         abbr: "KS", capital: "Topeka",         cities: ["Wichita", "Overland Park", "Olathe", "Lawrence"] },
  { name: "Kentucky",       abbr: "KY", capital: "Frankfort",      cities: ["Louisville", "Lexington", "Bowling Green", "Owensboro"] },
  { name: "Louisiana",      abbr: "LA", capital: "Baton Rouge",    cities: ["New Orleans", "Shreveport", "Lafayette", "Lake Charles"] },
  { name: "Maine",          abbr: "ME", capital: "Augusta",        cities: ["Portland", "Lewiston", "Bangor", "Biddeford"] },
  { name: "Maryland",       abbr: "MD", capital: "Annapolis",      cities: ["Baltimore", "Frederick", "Rockville", "Gaithersburg"] },
  { name: "Massachusetts",  abbr: "MA", capital: "Boston",         cities: ["Worcester", "Springfield", "Cambridge", "Lowell"] },
  { name: "Michigan",       abbr: "MI", capital: "Lansing",        cities: ["Detroit", "Grand Rapids", "Ann Arbor", "Flint"] },
  { name: "Minnesota",      abbr: "MN", capital: "Saint Paul",     cities: ["Minneapolis", "Rochester", "Duluth", "Bloomington"] },
  { name: "Mississippi",    abbr: "MS", capital: "Jackson",        cities: ["Gulfport", "Hattiesburg", "Biloxi", "Meridian"] },
  { name: "Missouri",       abbr: "MO", capital: "Jefferson City", cities: ["Kansas City", "St. Louis", "Springfield", "Columbia"] },
  { name: "Montana",        abbr: "MT", capital: "Helena",         cities: ["Billings", "Missoula", "Great Falls", "Bozeman"] },
  { name: "Nebraska",       abbr: "NE", capital: "Lincoln",        cities: ["Omaha", "Bellevue", "Grand Island", "Kearney"] },
  { name: "Nevada",         abbr: "NV", capital: "Carson City",    cities: ["Las Vegas", "Henderson", "Reno", "Sparks"] },
  { name: "New Hampshire",  abbr: "NH", capital: "Concord",        cities: ["Manchester", "Nashua", "Derry", "Dover"] },
  { name: "New Jersey",     abbr: "NJ", capital: "Trenton",        cities: ["Newark", "Jersey City", "Paterson", "Atlantic City"] },
  { name: "New Mexico",     abbr: "NM", capital: "Santa Fe",       cities: ["Albuquerque", "Las Cruces", "Rio Rancho", "Roswell"] },
  { name: "New York",       abbr: "NY", capital: "Albany",         cities: ["New York City", "Buffalo", "Rochester", "Syracuse"] },
  { name: "North Carolina", abbr: "NC", capital: "Raleigh",        cities: ["Charlotte", "Greensboro", "Durham", "Asheville"] },
  { name: "North Dakota",   abbr: "ND", capital: "Bismarck",       cities: ["Fargo", "Grand Forks", "Minot", "West Fargo"] },
  { name: "Ohio",           abbr: "OH", capital: "Columbus",       cities: ["Cleveland", "Cincinnati", "Toledo", "Akron"] },
  { name: "Oklahoma",       abbr: "OK", capital: "Oklahoma City",  cities: ["Tulsa", "Norman", "Broken Arrow", "Edmond"] },
  { name: "Oregon",         abbr: "OR", capital: "Salem",          cities: ["Portland", "Eugene", "Hillsboro", "Bend"] },
  { name: "Pennsylvania",   abbr: "PA", capital: "Harrisburg",     cities: ["Philadelphia", "Pittsburgh", "Allentown", "Erie"] },
  { name: "Rhode Island",   abbr: "RI", capital: "Providence",     cities: ["Warwick", "Cranston", "Pawtucket", "Newport"] },
  { name: "South Carolina", abbr: "SC", capital: "Columbia",       cities: ["Charleston", "Greenville", "Myrtle Beach", "Spartanburg"] },
  { name: "South Dakota",   abbr: "SD", capital: "Pierre",         cities: ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings"] },
  { name: "Tennessee",      abbr: "TN", capital: "Nashville",      cities: ["Memphis", "Knoxville", "Chattanooga", "Clarksville"] },
  { name: "Texas",          abbr: "TX", capital: "Austin",         cities: ["Houston", "San Antonio", "Dallas", "El Paso"] },
  { name: "Utah",           abbr: "UT", capital: "Salt Lake City", cities: ["Provo", "West Jordan", "Ogden", "St. George"] },
  { name: "Vermont",        abbr: "VT", capital: "Montpelier",     cities: ["Burlington", "Rutland", "Barre", "Brattleboro"] },
  { name: "Virginia",       abbr: "VA", capital: "Richmond",       cities: ["Virginia Beach", "Norfolk", "Alexandria", "Roanoke"] },
  { name: "Washington",     abbr: "WA", capital: "Olympia",        cities: ["Seattle", "Spokane", "Tacoma", "Bellevue"] },
  { name: "West Virginia",  abbr: "WV", capital: "Charleston",     cities: ["Huntington", "Morgantown", "Parkersburg", "Wheeling"] },
  { name: "Wisconsin",      abbr: "WI", capital: "Madison",        cities: ["Milwaukee", "Green Bay", "Kenosha", "Appleton"] },
  { name: "Wyoming",        abbr: "WY", capital: "Cheyenne",       cities: ["Casper", "Laramie", "Gillette", "Rock Springs"] }
];
